### ISSUE TITLE
MCZ income analysis

### ISSUE THREAD

**Issue by grlurton** [grlurton/DRC_HRH#14]
that there is much difference/inequalities between what each one receives and that the difference seems to be driven by factors  that are not salary+pdr (almost all receive them and seem quite uniform). ?

**Comment by grlurton** [comment]
graphs of composition of outcome for MCZ by province

age

**Comment by mariapaola5** [comment]
@grlurton a few things on this:
- (as mentioned on skype): x axis=USD? there may be something wrong..
- could you add % of each component? it makes it much clearer to read and compare across lines
- Nico says he'd take out income from outside health sector in this type of analysis .. I guess his argument is that those revenues are less policy relevant -- not sure I agree it's a good reason to take them off. What do you think?
- Also, thinking of what Nico seems to be looking at: could we create two profiles for the first and last (lower and higher income) MCZ and see what their differences are? like, creating two profiles ex-post looking at those two guys and then commenting on them like if they were two of our random profiles.. see what I mean? is that bad because it's just two cases and not really meaningful...? (ok, just saying. will go to bed....)
