### ISSUE TITLE
verifier 11 pharmaciens in Bandundu

### ISSUE THREAD

**Issue by grlurton** [grlurton/DRC_HRH#20]
Donnee pas coherente

**Comment by grlurton** [comment]
@mariapaola5 this is hgr in kikwit nord. all 15 pharmaciens are actually preparateurs. Huge facility for all cadres. my feeling is it is in PER data, can you check ?

**Comment by grlurton** [comment]
makes #18 even more relevant @mariapaola5

**Comment by mariapaola5** [comment]
@grlurton -- nope. PER (i.e. Francoise's interviews) where only in Katanga and Equateur. Not sure PER fieldwork was done in Bandudu at all.
But if it looks fine because the facility is big and all, then it's fine. I'll check for the classification though -- in this case, grouping pharmacists with preposés à la pharmacie may be misleading. 

```
  From: Grégoire Lurton <notifications@github.com>
```

 To: grlurton/DRC_HRH DRC_HRH@noreply.github.com 
Cc: mariapaola5 mpbertone@yahoo.com 
 Sent: Tuesday, January 6, 2015 9:50 PM
 Subject: Re: [DRC_HRH] verifier 11 pharmaciens in Bandundu (#20)

@mariapaola5 this is hgr in kikwit nord. all 15 pharmaciens are actually preparateurs. Huge facility for all cadres. my feeling is it is in PER data, can you check ?—

**Comment by mariapaola5** [comment]
i know! working on something else now -- it waited until now can wait tomorrow.

**Comment by grlurton** [comment]
yep no worries.
